[package]
name = "bootloader"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "bootloader"
test = false
bench = false

[dependencies]
log = { version = "0.4.33", features = [
  "max_level_debug",
  "release_max_level_info",
] }

[target.'cfg(target_arch = "riscv64")'.dependencies]
sbi-rt = "0.0.4"
