name: Deploy Cargo Docs

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: riscv64gc-unknown-none-elf

      - name: Build documentation
        run: cargo doc --no-deps

      - name: Add redirect index.html
        run: |
          echo "<meta http-equiv=\"refresh\" content=\"0; url=kernel/index.html\">" > target/riscv64gc-unknown-none-elf/doc/index.html

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "target/riscv64gc-unknown-none-elf/doc"

  deploy:
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
